### PR TITLE
[I-10] Fix/ Dialog Save State and dialog is not aligned properly

### LINKED ISSUE #10: Screen rotation wipes all the data from the dialog
### Description
When a screen rotates `Huddle` won't save the state and the dialog will be blank. After that, it can't be dismissed. The only way to solve that you have to kill the app. Also, in the `horizontal` state the dialog isn't in the center. 

### Screenshots
<p align="center">
  <kbd>preview</kbd>
<kbd>preview</kbd>

### PR DESCRIPTION
**Pull request by ardiien**
### Notes:
```
- center dialog
- remove fix size of dialog width
- adjust dialog width calculations
- remove dimen default_dialog_width
- set Gravity to Center
- apply dialog full screen and floating parameters
```

### Known issues:
- [x] save state after rotation
- [ ] ~~listeners can't stay alive after rotation~~

> ⚠️ This PR will not cover save state after rotation issue for listeners.

### CODE REVIEW

File: huddle/src/main/java/team/uptech/huddle/util/extension/ActivityExtensions.kt [hunk 1]
```diff
@@ -2,21 +2,23 @@ package team.uptech.huddle.util.extension
...
   display.getMetrics(metrics)
 
-  val heightPixels = metrics.heightPixels
   val widthPixels = metrics.widthPixels
+  val heightPixels = metrics.heightPixels
 
-  return min(heightPixels, widthPixels)
+  return when (display.rotation) {
+    Surface.ROTATION_0, Surface.ROTATION_180 -> widthPixels
+    Surface.ROTATION_90, Surface.ROTATION_270 -> widthPixels
```
Comment (ardiien) [inline huddle/src/main/java/team/uptech/huddle/util/extension/ActivityExtensions.kt]: merge into single `case`

File: huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt [hunk 2]
```diff
@@ -89,20 +79,15 @@ inline fun <reified T : DialogFragment> tryAddDialogToStack(
...
 fun Dialog.setWidthRelativeToParent(activity: Activity?, percentage: Int) {
   val screen = activity ?: return
 
-  val defaultDialogWidth = screen.resources.getDimension(R.dimen.dialog_default_width)
-  val dynamicWidth = (percentage / 100.0f * screen.getMinWidthValue())
+  val dynamicWidth = (percentage / 100.0f * screen.getScreenWidth())
 
-  val calculatedDialogWidth = min(defaultDialogWidth, dynamicWidth).roundToInt()
-  window?.setLayout(calculatedDialogWidth, ViewGroup.LayoutParams.WRAP_CONTENT)
+  window?.setGravity(Gravity.CENTER or Gravity.CENTER_HORIZONTAL)
```
Comment (ardiien) [inline huddle/src/main/java/team/uptech/huddle/util/extension/DialogExtensions.kt]: `Gravity.CENTER` is enough

**Review by ernesoglu — APPROVED** [review]
